import { REPLICAD_DOCS_BASE_FUNCTIONS, REPLICAD_DOCS_WIKI, REPLICAD_DOCS_REMAINING_EXAMPLES_PART_1, REPLICAD_DOCS_REMAINING_EXAMPLES_PART_2, REPLICAD_DOCS_REMAINING_EXAMPLES_PART_3, REPLICAD_DOCS_MISCELLANEOUS_CONTENT, REPLICAD_EXAMPLES } from "./replicadDocsLibrary";

export const REPLICAD_LEVEL_1_DOCS = REPLICAD_DOCS_BASE_FUNCTIONS;
export const REPLICAD_LEVEL_2_DOCS = REPLICAD_DOCS_BASE_FUNCTIONS + REPLICAD_EXAMPLES;
export const REPLICAD_LEVEL_3_DOCS = REPLICAD_DOCS_BASE_FUNCTIONS + REPLICAD_DOCS_WIKI;
export const REPLICAD_LEVEL_4_DOCS = REPLICAD_DOCS_BASE_FUNCTIONS + REPLICAD_DOCS_WIKI + '\n\n' + REPLICAD_EXAMPLES;
export const REPLICAD_LEVEL_5_DOCS = REPLICAD_DOCS_BASE_FUNCTIONS + REPLICAD_DOCS_WIKI + '\n\n' + REPLICAD_EXAMPLES + '\n\n' + REPLICAD_DOCS_REMAINING_EXAMPLES_PART_1;
export const REPLICAD_LEVEL_6_DOCS = REPLICAD_DOCS_BASE_FUNCTIONS + REPLICAD_DOCS_WIKI + '\n\n' + REPLICAD_EXAMPLES + '\n\n' + REPLICAD_DOCS_REMAINING_EXAMPLES_PART_1 + '\n\n' + REPLICAD_DOCS_REMAINING_EXAMPLES_PART_2;
export const REPLICAD_LEVEL_7_DOCS = REPLICAD_DOCS_BASE_FUNCTIONS + REPLICAD_DOCS_WIKI + '\n\n' + REPLICAD_EXAMPLES + '\n\n' + REPLICAD_DOCS_REMAINING_EXAMPLES_PART_1 + '\n\n' + REPLICAD_DOCS_REMAINING_EXAMPLES_PART_2 + '\n\n' + REPLICAD_DOCS_REMAINING_EXAMPLES_PART_3;
export const REPLICAD_LEVEL_8_DOCS = REPLICAD_DOCS_BASE_FUNCTIONS + REPLICAD_DOCS_WIKI + '\n\n' + REPLICAD_EXAMPLES + '\n\n' + REPLICAD_DOCS_REMAINING_EXAMPLES_PART_1 + '\n\n' + REPLICAD_DOCS_REMAINING_EXAMPLES_PART_2 + '\n\n' + REPLICAD_DOCS_REMAINING_EXAMPLES_PART_3 + '\n\n' + REPLICAD_DOCS_MISCELLANEOUS_CONTENT;


export const REPLICAD_DOCS = REPLICAD_LEVEL_1_DOCS;